### ISSUE TITLE
these look great

### ISSUE THREAD

**Issue by satra** [miykael/nipype_tutorial#1]
@miykael - just wanted to say how awesome these new tutorials and docker environments are!

**Comment by miykael** [comment]
@satra, thank you very much. I worked for the last two weeks just on these tutorials and on the docker environments and I'm very happy about how it came out.

But I couldn't have done it without the input, notebooks, Dockerfiles  and code snippets from you, @chrisfilo, @oesteban and @mwaskom. Any feedback from you guys and the community on how to improve the tutorial is highly appreciated.

**Comment by chrisfilo** [comment]
This looks amazing - excellent work! Bravo!

**Comment by satra** [comment]
@miykael - one thing i ran into as i did a tutorial using this recently is that it uses an older version of nipype. would be nice to use current master.

**Comment by satra** [comment]
btw i also used level0 to do a nilearn tutorial!

**Comment by miykael** [comment]
Thanks @chrisfilo! 

Right @satra, I will update the Dockerfile to install Nipype directly from github.
Nice about the nilearn tutorial. I also saw that you already showed some part of the tutorial at the brainhack global in Boston (https://twitter.com/leaddbs/status/838065826435592192)

**Comment by miykael** [comment]
Btw, there should be a youtube video eventually from my nipype tutorial during the brainhack in Zürich, but I'm not sure if it's the best to advertise the tutorial. It was my first tutorial and I think I lost most of the listeners will showing how to setup docker on Windows :-)

**Comment by miykael** [comment]
As I have you here, the beginner's guide and the tutorial both use google analytics. During the last 5 years, I already had 23'552 users with 47'521 sessions on the beginner's guide. I also just started to track my github repos [miykael/traffic_info_github](https://github.com/miykael/traffic_info_github), views and clones.

Do you have any interest in such kind of data? I have no idea if this would help with getting funding or similar. But if so, how could I best share those information with you?

**Comment by satra** [comment]
@miykael - yes that would be super helpful for various reports when the time comes.
