### ISSUE TITLE
ENH: Add new default `Function` behavior

### ISSUE THREAD

**Issue by effigies** [miykael/nipype_tutorial#10]
This is mostly a reminder to myself to update [`notebooks/basic_function_nodes.ipynb`](https://miykael.github.io/nipype_tutorial/notebooks/basic_function_nodes.html) to incorporate nipy/nipype#1918 default behaviors.

**Comment by effigies** [comment]
The change is that you can now leave out `input_names` and `output_names`. `input_names` will be automatically derived from inspecting the function, and `output_names = ['out']` by default.

The only case in which there is unusual behavior is that if you have:

```Python
def f(a, b=2):
    return a+b

fun = Function(input_names=['a'], function=f)
fun.inputs.a = 1
fun.inputs.b = 10

out = fun.run().outputs.out
```

`out` here will be 3, not 10. `b` is not passed to the function because it is not in `input_names`. I don't see why this would be useful behavior, but it's possible somebody depends on it. nipy/nipype#2520 will throw `TraitError`s to let users know that these inputs can't be changed. So I guess we've decided it counts as a feature.

**Comment by miykael** [comment]
Thanks @effigies, I've updated the tutorial with https://github.com/miykael/nipype_tutorial/pull/75
