### ISSUE TITLE
notebooks assume loads of CPU cores are available

### ISSUE THREAD

**Issue by jooh** [miykael/nipype_tutorial#104]
I am currently getting a test_notebooks 2 fail because notebooks/example_preprocessing_short attempts to spin up MultiProc with 8 processors, which is more than I have. Searching the repo, n_procs is set variously to 2, 4, 5 (?), and 8.

A quick easy fix would be to set them all to 2. This would make things needlessly slow for many users however.

A more elegant solution would be to have the notebooks retrive an n_procs environment variable, which would default to 2 but would be available to user modification by passing the -e flag during docker run.

There doesn't seem to be a robust way to programmatically retrieve the number of available cores in python. :(

**Comment by miykael** [comment]
@jooh - Thank you for pointing this out. You're right, we should have this lower than 8 and ideally adjusted to the local machine. By the way, n_proc stands rather for the number of jobs / threads than CPUs. So, usually a dual core should be capable to run 4 processors. But for most example in this workshop 2-4 parallel jobs should be way enough.

I think I saw once a pythonic way to retrieve the number of cores/possible threads. I will look into that and change the notebooks accordingly.

**Comment by miykael** [comment]
It seems that the following command could be used to get the number of possible threads:
```python
import multiprocessing
n_proc = multiprocessing.cpu_count()
print(n_proc)
```

**Comment by miykael** [comment]
@jooh - If I'm not mistaken, than the n_procs issue is only in the [nipype_tutorial](https://github.com/miykael/nipype_tutorial), so I will need to change the notebooks there.

And I just realized that it's also possible to omit the n_procs command, in which case it uses all available threads. So, instead of:

```python
wf.run(plugin='MultiProc', plugin_args={'n_procs': 2})
```

just

```python
wf.run(plugin='MultiProc')
```

Do you think that's good enough or would you prefer that it's fixed to a particular value?

**Comment by miykael** [comment]
@jooh - I only saw now, that we are already in the `nipype_tutorial` repo. I reduced now the number of parallel threads to 4, which should work on almost all machines (4 threads = dual-core machine).

Please tell me if this nonetheless causes issues with your setup. And thanks again for pointing it out.

**Comment by jooh** [comment]
Well, this is embarrassing. I think the entire problem here was that I had neglected to increase the amount of RAM available to Docker. The test passes now. As you point out above, I think the MultiProc setting may have been a red herring since it controls the number of threads, not the number of CPUs. The real issue was insufficient RAM. Sorry about all the confusion. Feel free to close this.

**Comment by miykael** [comment]
No problem @jooh. It was anyhow a good idea to decrease the number of threads. I forgot that they were on 8. :-)
