### ISSUE TITLE
Tipps for Production

### ISSUE THREAD

**Issue by ASVBPREAUBV** [miykael/nipype_tutorial#109]
Thanks for the great tutorial! we work very closely with your guys material.
Im not sure if this is the right place to ask.

Can you give tips/resources for using nipype in production?
My initial thought was to run is all in docker-containers, but the neurodocker-images dont play nicely with for example gunicorn.
Im trying to use nipype in a webserver-environment.

**Comment by djarecka** [comment]
@ASVBPREAUBV - personally I don't have experience working with gunicorn and not sure what kind of problem you might have with this system. 

Probably the best chances to reach people who are using various systems you might have by posting on [neurostars](https://neurostars.org/). Please, write a bit more about the problems with docker.

**Comment by ASVBPREAUBV** [comment]
@djarecka tanks for the fast reply. will do.

**Comment by miykael** [comment]
This issue was now addressed under https://neurostars.org/t/nipype-with-a-webserver-in-docker/2271

I will therefore close this issue here. @ASVBPREAUBV feel free to reopen it, if necessary.
