### ISSUE TITLE
Nipype Workflow execution using PBS

### ISSUE THREAD

**Issue by singlakdeepak** [miykael/nipype_tutorial#111]
Hi

I am trying to run a workflow on HPC and it has PBS for job scheduling. As much as I know, Nipype distributes the nodes in the workflow graph according to the resources available. While running a workflow, I use this code:
```
Reg_WorkFlow.run('PBSGraph', plugin_args={'template':template_nipype_job,
                                                    'dont_resubmit_completed_jobs': True})
```
But I am not sure whether it distributes the inputs across the available resources or whether all the inputs run on a single HPC node. For example, if I have 1000 inputs, whether all the inputs will load on a single HPC node or can I distribute the inputs across the HPC nodes?

**Comment by miykael** [comment]
Hi @singlakdeepak - I unfortunately don't have the expertise to help you with this issue, but you should post your question https://neurostars.org/. I'm sure that somebody can give you an answer in no time. Good luck!

**Comment by singlakdeepak** [comment]
Hi @miykael - I tried at Neurostars and haven't received a single reply from 2 days. Can you let me know of any other channel where I can ask the same question?

**Comment by miykael** [comment]
Hi @singlakdeepak, is this issue still open or can we close it?

**Comment by singlakdeepak** [comment]
Yes @miykael, you can close the issue.
