### ISSUE TITLE
Range functions in mapnode tutorial not working

### ISSUE THREAD

**Issue by AkiNikolaidis** [miykael/nipype_tutorial#12]
I found that the mapnode tutorial gives some errors when using the range function in python 3.6, perhaps changing this to a list would solve this issue?

**Comment by AkiNikolaidis** [comment]
Submitted a PR with this change

**Comment by miykael** [comment]
Hi @AkiNikolaidis, I'm not sure if I've missed your PR. But the tutorial was updated to python 3.5. Do you know if the issue is still present?
