### ISSUE TITLE
datalad: [ERROR ] could not perform all requested actions: None [get.py:__call__:380]

### ISSUE THREAD

**Issue by avatar-lavventura** [miykael/nipype_tutorial#133]
I am following this tutorial (https://miykael.github.io/nipype_tutorial/notebooks/example_preprocessing.html). I was not able to download the dataset. How could I fix this error?

```
$ datalad get -J 4 /data/ds000114/derivatives/fmriprep/sub-*/anat/*preproc.nii.gz \
                /data/ds000114/sub-*/ses-test/func/*fingerfootlips*

[WARNING] ignored non-existing paths: ['/data/ds000114/derivatives/fmriprep/sub-*/anat/*preproc.nii.gz']
Got nothing new
[ERROR  ] could not perform all requested actions: None [get.py:__call__:380]
```

**Comment by miykael** [comment]
HI @avatar-lavventura,

`datalad get` tries to download the data inside a dataset folder, i.e. you first need to install the dataset scaffold/"folder structure" with the command `datalad install -r ///workshops/nih-2017/ds000114`.

If you're in your home folder, this means it will install `ds000114` in your home folder. To then use the `datalad get` command, you need to link to the files you want. In the case above, you would need to use the following command:

```
datalad get -J 4 /home/user/ds000114/derivatives/fmriprep/sub-*/anat/*preproc.nii.gz \
                 /home/user/ds000114/sub-*/ses-test/func/*fingerfootlips*
```

For more information, check [this section](https://miykael.github.io/nipype_tutorial/notebooks/introduction_dataset.html).

**Comment by miykael** [comment]
Sorry, my assumption was that you ran the `datalad get` command outside the docker image `miykael/nipype_tutorial`. Did you get the error inside the docker container?

**Comment by avatar-lavventura** [comment]
Yes I was running `datalad get` command outside of the docker image and your guide help me to fix it.
