### ISSUE TITLE
dMRI: Connectivity - Camino, CMTK, FreeSurfer workflow error: The 'outputtracts' trait of a ProcStreamlinesInputSpec instance must be a boolean, but a value of 'oogl' <type 'str'> was specified.

### ISSUE THREAD

**Issue by avatar-lavventura** [miykael/nipype_tutorial#134]
I am not sure it is correct place to ask, if it is not I can remove the opened issue.

--------

I am trying to run `dMRI: Connectivity - Camino, CMTK, FreeSurfer` workflow 
that is provided under nipype's website under tutorial : workflows, please see its [link](https://nipype.readthedocs.io/en/0.12.0/users/examples/dmri_connectivity.html).

Please see [sourceCode.py](
https://nipype.readthedocs.io/en/0.12.0/_downloads/dmri_connectivity.py), which is given as the full source code of the example.

```
$ wget -c http://fsl.fmrib.ox.ac.uk/fslcourse/downloads/fdt.tar.gz
$ tar -xzvf fdt.tar.gz  #extracted folders are fdt1 and fdt2
# updated following line data_dir = op.abspath('fsl_course_data/fdt/') with data_dir = op.abspath('fdt2') on the source code
$ grep -rn 'oogl'
Binary file fdt1/subj1_preproc/dwidata.nii.gz matches
$ python sourceCode.py
Traceback (most recent call last):
  File "sourceCode.py", line 194, in <module>
    procstreamlines.inputs.outputtracts = 'oogl'
  File "/home/netlab/.local/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'outputtracts' trait of a ProcStreamlinesInputSpec instance must be a boolean, but a value of 'oogl' <type 'str'> was specified.
```

**[Q]** How could I fix the error I am having? Is there anything am I doing wrong?

**Comment by miykael** [comment]
Hi @avatar-lavventura, the tutorial on the main homepage is unfortunately not connected with this repo. So your question should be best addressed on https://github.com/nipy/nipype/issues (sorry for sending you back and forth).

Also, you're link is pointing to the homepage version 0.12 ([https://nipype.readthedocs.io/en/**0.12.0**/users/examples/dmri_connectivity.html](https://nipype.readthedocs.io/en/0.12.0/users/examples/dmri_connectivity.html)), I recommend to look at the newest version under [https://nipype.readthedocs.io/en/**latest**/users/examples/dmri_connectivity.html](https://nipype.readthedocs.io/en/latest/users/examples/dmri_connectivity.html). But I don't think that this solves your issue.

**Side note:** The example workflows on the main homepage are currently not tested. This is unfortunate and we try to correct this in the future. But this could mean that the example itself is broken. Unfortunately, I'm not an export with diffusion imaging and don't understand what this `oogl` stands for. 

Good luck!

**Comment by miykael** [comment]
I think this issue is discussed now in https://github.com/nipy/nipype/issues/2742 and therefore can be closed here, correct?
