### ISSUE TITLE
Error with MCFLIRT in hands-on 1: preprocessing

### ISSUE THREAD

**Issue by roeysc** [miykael/nipype_tutorial#140]
Hi Miykael,

First of all, thank you so much for all the effort you put into this wonderful tutorial. It's so useful, and I highly appreciate it.

As [I posted in NeuroStars](https://neurostars.org/t/error-using-fsls-mcflirt-with-mean-img-in-nipype/3780), I encountered a problem running the tutorial code for the hands-on preprocessing. Specifically, I get the following error:

traits.trait_errors.TraitError: The trait ‘mean_img’ of a MCFLIRTOutputSpec instance is an existing file name, but the path ‘/home/roey/nipype_data/output/work_preproc/mcflirt/asub-07_ses-test_task-fingerfootlips_bold_roi_mcf.nii.gz_mean_reg.nii.gz’ does not exist.

which suggests that the missing file that was expected as an output of MCFLIRT has the “.nii.gz” extension twice in its name. Indeed, a different file was actually created, with the more reasonable name:

/home/roey/nipype_data/output/work_preproc/mcflirt/asub-07_ses-test_task-fingerfootlips_bold_roi_mcf_mean_reg.nii.gz

Am I missing something in the way I configured the pipeline? Or is there possibly some mismatch between two pieces of code in Nipype?

Many thanks in advance,
Roey

**Comment by roeysc** [comment]
Update:
I think the problem is in using FSL 6.0, in which the output file of the -meanvol option is created without the redundant ".nii" or ".nii.gz" suffix inside the file name, and this is not what MCFLIRT expects (according to the "_gen_outfilename" method in the MCFLIRT class definition under the preprocess.py file).
I will therefore uninstall FSL 6.0 and work with FSL 5.0 instead.
Roey

**Comment by miykael** [comment]
Hi @roeysc, the dublication of `nii.gz` is usually not an issue, nipypye and FSL were always very happy to just prolongate a filename. But you're right, the issue could very well be due to FSL 6.0. Unfortunately, I didn't had time yet to look into this.
Did the switch to FSL 5.0 solve your error?

**Comment by roeysc** [comment]
Hi @miykael, yes, the switch to FSL 5.0 solved the error, and I could go on with the rest of the workflow.
Thanks!

**Comment by miykael** [comment]
Perfect. Thank you for the update. I will close this issue for now. But should you have any more questions or issues, don't hesitate to open a new one.
