### ISSUE TITLE
build image fail due to permission issue

### ISSUE THREAD

**Issue by zuxfoucault** [miykael/nipype_tutorial#143]
![Screen Shot 2019-07-12 at 17 39 11](https://user-images.githubusercontent.com/3050531/61119783-24417a80-a4ce-11e9-8dc3-b91c0eb4c39b.png)

Basically, I didn't touch any default setting

**Comment by zuxfoucault** [comment]
workaround: https://github.com/kaczmarj/neurodocker/issues/286

**Comment by miykael** [comment]
Thank you for pointing this out. This issue will be corrected with https://github.com/miykael/nipype_tutorial/pull/144.
