### ISSUE TITLE
Script not in expected location

### ISSUE THREAD

**Issue by arokem** [miykael/nipype_tutorial#17]
The second cell in the `example_normalize` notebook looks for:

`%load /opt/tutorial/notebooks/scripts/ANTS_registration.py`

But the file is not in this location. Replacing with: 

`%load scripts/ANTS_registration.py`

seems to work.

At least on the `satra/nhw17` docker image.

**Comment by miykael** [comment]
Hi @arokem, good point.

The notebook was written for the docker image ``satra/nih-workshop-2017``. I changed the path with https://github.com/miykael/nipype_tutorial/commit/038eacb8b9ac60189a15e6461287f5c1a293d266 to a relative path, so that it should work for other docker images too.

Thanks!
