### ISSUE TITLE
add exercises to the tutorial

### ISSUE THREAD

**Issue by miykael** [miykael/nipype_tutorial#2]
@satra had the great idea to add some exercises within the tutorials. The best idea to hide the solution is probably to store it in a python script, and call it with ``%load answer01.py``.

**Comment by satra** [comment]
@miykael - we are now doing this in some of the other datascience notebooks we have created. @djarecka - can show you how to use it.

**Comment by miykael** [comment]
Great, I'm very interested in doing something like this.

@djarecka, I saw already that there is a "create/remove solution" button in satra's docker image nhw17, but I haven't figured out yet how to add solutions and how to actually hide them. Do you have a working example/pointer?

**Comment by satra** [comment]
@miykael - if you download the latest nhw17 and go to /repos - try out the neuro* notebooks

`docker run -it --rm -p 8888:8888 20170831T2153`

**Comment by miykael** [comment]
@satra, thanks. I see, it looks really cool and is good to use.

But if I'm not mistaken, this exercise function doesn't work for the html version of the notebooks, i.e. the gh-pages. In the html version of the notebook it just expands the solutions. I'm not sure if there is an alternative solution to this or if this is acceptable.

**Comment by satra** [comment]
@miykael - indeed it doesn't work with the html render. perhaps a question worth asking the jupyter devs. it seems they could enable it for the html output as well.

**Comment by miykael** [comment]
This issue is adressed in https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1286.

**Comment by miykael** [comment]
I will close this issue, as we've already included some exercises.
