### ISSUE TITLE
The link doesn't work

### ISSUE THREAD

**Issue by HaiyangJin** [miykael/nipype_tutorial#22]
![capture](https://user-images.githubusercontent.com/7224496/30263559-79bba22e-9729-11e7-9ae0-6039fcfc27d8.PNG)

**Comment by miykael** [comment]
Thanks @HaiyangJin, I corrected it with https://github.com/miykael/nipype_tutorial/commit/0f83176e85fd4f028717260386af8c9bc0baec47
