### ISSUE TITLE
docker pull download issue

### ISSUE THREAD

**Issue by Armin12** [miykael/nipype_tutorial#23]
Hi, to use the nipype should I docker pull nipype/nipype_level3 or it is any other file?
I tried docker pull to download nipype/nipype_level3 but the download wasn't finished. It stopped without being completed. The name of image was then in the image list but when I run the image to give me a URL, the workflow was not properly loaded. What is the problem? Is that because of the VM disk space? If yes, how can I solve it? Thanks

**Comment by miykael** [comment]
Hi @Armin12,
You mention the image ``nipype/nipype_level3``, do you perhaps mean ``miykael/nipype_level3``? In any case, if the download didn't finish, I recommend to retry it again till it works.
But the image ``miykael/nipype_level3`` is not the most current one. I recommend to use ``miykael/nipype_tutorial`` to use for the nipype tutorial. It might makes also sense that you create your own environment, specific adapted to your needs. For this I recommend https://github.com/kaczmarj/neurodocker. Good luck!

**Comment by Armin12** [comment]
Thank you so much @miykael
