### ISSUE TITLE
Suggestion to add a link for the data set ds000114

### ISSUE THREAD

**Issue by athanell** [miykael/nipype_tutorial#25]
Hello @miykael, 
you might consider adding a link for the dataset ds00014 that is required in 
[https://miykael.github.io/nipype_tutorial/notebooks/introduction_docker.html](url)
Or maybe even better point to the Tutorial Dataset section of [https://miykael.github.io/nipype_tutorial/notebooks/introduction_dataset.html](url) since only a small part of the data is necessary 
Thank you

**Comment by miykael** [comment]
Thanks @athanell, I changed the links with https://github.com/miykael/nipype_tutorial/commit/5b31157f7d08e79bf8c18fea052453532a692df7 to link to the openfmri homepage of ds000114.
