### ISSUE TITLE
Possible mistake in the basic workflow tutorial? 

### ISSUE THREAD

**Issue by athanell** [miykael/nipype_tutorial#26]
Hello @miykael, 

I think there is a small bug in the workflow tutorial. [https://miykael.github.io/nipype_tutorial/notebooks/basic_workflow.html](url)

In the part of the code 
`# Masking process
mask = fsl.ApplyMask(
    in_file="/data/ds000114/sub-02/ses-test/anat/sub-02_ses-test_T1w.nii.gz",
    out_file="/output/sub-02_T1w_smooth_mask.nii.gz",
    mask_file="/output/sub-02_T1w_brain_mask.nii.gz")
mask.run()` 

the input file should be the smoothed file from the previous step, so the correct code should be like

`# Masking process
mask = fsl.ApplyMask(
    in_file="/output/sub-02_T1w_smooth.nii.gz",
    out_file="/output/sub-02_T1w_smooth_mask.nii.gz",
    mask_file="/output/sub-02_T1w_brain_mask.nii.gz")
mask.run()`

Could you check that out?

Thanks

**Comment by miykael** [comment]
Hi @athanell. Yes, you're right. Thank you for the pointer. I will just update it.

**Comment by miykael** [comment]
changed with https://github.com/miykael/nipype_tutorial/commit/9888874d099d0d1b0d72d6a36d1e107cb83cadc6
