### ISSUE TITLE
Can't run tutorial on docker (win 10)

### ISSUE THREAD

**Issue by hcp4715** [miykael/nipype_tutorial#44]
Hello, there,

Thanks a lot for developing this great tool!
I am trying to follow the tutorial, and install docker on my pc (win 10 pro., docker version: stable).

Everything goes well for the installation and downloading the images, but when I begin to run the tutorial: 
`docker run -it --rm -p 8888:8888 djarecka/nipype_tutorial jupyter notebook`

I got the following error message:

> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint jolly_heyrovsky (b5b199502a5938753852aeda72531d73e9824d2045dd11c12f8ff6ad7e4b5bc0): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8888:tcp:172.17.0.2:8888: input/output error.

**Comment by djarecka** [comment]
I've never had this problem, but it looks like restarting Docker and/or computer might work (see [discussion](https://github.com/docker/compose/issues/3277) . It's likely that someone else is using the specific port.

**Comment by miykael** [comment]
Additionally, to what @djarecka said, could it be possible that you have already a docker container running in the background that blocks the port 8888. `docker ps -a` will show you a list of all docker containers (currently running and stopped ones). Perhaps reseting those containers helps.

Also, does `docker run -it --rm -p 8888:8888 djarecka/nipype_tutorial bash` get you into the terminal console?

**Comment by hcp4715** [comment]
Hi, @djarecka @miykael ,
Thanks so much for your reply! I am new to docker and python. 
I used `docker ps -a` and found that I do have run some other container before. After restarted docker, that code can be executed.
but I encountered another problem: the powershell can't open the browser:
![capture](https://user-images.githubusercontent.com/7300419/36566611-4d02ab66-1824-11e8-975b-f7342a6fad1e.JPG)
I copied and pasted the url 'http://0.0.0.0:8888/?token=c8adaba9177db8af0cb19a91ba4f8fe18eed8120778f2d5c' to my brower, but it said "this page can't be reached", in both chrome and IE.
then, I searched for a solution (e.g. https://stackoverflow.com/questions/15632663/launch-ipython-notebook-with-selected-browser), but it seems that these answer all used the code in python, instead of windows powershell (correct me if I am wrong).

Many thanks.!

**Comment by miykael** [comment]
@hcp4715, the message about "No web browser found" is normal. I think it means that within the docker image, it couldn't find a web browswer. As you saw, the important part is the URL that you copied into your browswer.

But, on Windows you need to change the URL slightly, as the 0.0.0.0 IP adress will not work. We have a short description on how to do it [here](https://miykael.github.io/nipype_tutorial/notebooks/introduction_docker.html#Run-a-docker-image-on-Windows), but in short:
1. use `docker-machine ip` to find out your IP adress, e.g. `192.168.99.100`
2. replace the `0.0.0.0` in the URL with your IP adress. Your URL should then look something like this `http://192.168.99.100:8888/?token=0312c1ef3b61d7a44ff5346d3d150c23249a548850e13868`

PS: I'm not sure if you perhaps can also replace `0.0.0.0` by `localhost`

**Comment by hcp4715** [comment]
@miykael 
Thanks for your reply. After reading your reply, I realized that there is a Note on the introduction webpage.
But, the problem still there. When I type `docker-machine ip`, I didn't get an IP address, but an error message:
> Error: No machine name(s) specified and no "default" machine exists
I searched this error message, unfortunately, the results are not really helpful for: 
https://stackoverflow.com/questions/41319308/docker-does-not-have-default-machine-in-windows-10
https://stackoverflow.com/questions/39966083/docker-machine-no-machine-name-no-default-exists

I even followed the instruction on docker:
https://docs.docker.com/machine/drivers/hyper-v/
and tried `docker-machine create --driver hyperv vm`, and there was one machine called vm. Still, when I tried `docker-machine ip`, the same error showed.

**Comment by hcp4715** [comment]
@miykael 
I found the solution: just replace the `0.0.0.0` with `localhost`. 
This solution was found by chance: I run the jupyter lab using powershell, and when I stop running that, I found it also has similar message, in which the url is http://localhost:8888/?token......
so, I tried to run the code (`docker run -it --rm -p 8888:8888 djarecka/nipype_tutorial jupyter notebook`) again, and it open the jupyter book!

**Comment by djarecka** [comment]
@hcp4715 - nice job! happy that it works for you now. closing the issue.
