### ISSUE TITLE
improving testing with CircleCI

### ISSUE THREAD

**Issue by djarecka** [miykael/nipype_tutorial#47]
should improve testing:
- [x] improve datalad command (email from Yarik)
- [ ]  retry build in circleCI (copy from nipype did not retry)
- [x]  increasing timeout for notebooks (but where??)

**Comment by djarecka** [comment]
datalad command has been changed in #50

**Comment by miykael** [comment]
@djarecka - I think this issue can be closed as circleCI works well for the moment, not optimal but good enough.

Also, concerning the notebook timeout, we could increase the `no_output_timeout` (https://github.com/miykael/nipype_tutorial/blob/master/.circleci/config.yml#L19) from 90m to 120m. The longest example currently takes ~85min. What do you think?

**Comment by miykael** [comment]
I increased the timeout period to 120min with https://github.com/miykael/nipype_tutorial/pull/67.

**Comment by djarecka** [comment]
Sure, we can increase it. I think sometimes I had an issue with other (not circleCI) timeouts, but I might be wrong. Doesn't hurt to increase this one.

And sure we can close it.
