### ISSUE TITLE
add tests for tutorials

### ISSUE THREAD

**Issue by satra** [miykael/nipype_tutorial#5]
we should connect this with circle ci, so that we can check that the tutorial works cleanly as docker containers are updated.

**Comment by miykael** [comment]
That's a brilliant idea. I haven't looked into circle ci (or testing in general), yet. But I'm very eager to learn. Do you have some nice pointers?

Also, how would you create tests for notebooks? Something like this http://blog.thedataincubator.com/2016/06/testing-jupyter-notebooks/?
