### ISSUE TITLE
using an older version of DataLad in a Docker image

### ISSUE THREAD

**Issue by djarecka** [miykael/nipype_tutorial#52]
I [ask for an older version of DataLad](https://github.com/miykael/nipype_tutorial/blob/master/Dockerfile#L120), due to an issue described [here](https://github.com/datalad/datalad/issues/2272). Waiting for a conclusion from DataLad team if they will keep this "feature" or not.

**Comment by miykael** [comment]
Problem was solved with the version [0.9.3](https://github.com/datalad/datalad/releases/tag/0.9.3) of datalad. Scripts were updated with https://github.com/miykael/nipype_tutorial/commit/f76a56e9c642fa3b0014947e35bbf1f2fbc37c9a.
