### ISSUE TITLE
error from the current version of matplotlib

### ISSUE THREAD

**Issue by djarecka** [miykael/nipype_tutorial#53]
Some of the notebooks don't work with the current version of matplotlib due to some `AttributeError` in `matplotlib.cm`, see more in [circleci output](https://circleci.com/gh/djarecka/nipype_tutorial/50?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

As a very temporary fix, I'm [asking for an older version of matplotlib](https://github.com/miykael/nipype_tutorial/blob/master/Dockerfile#L111)

**Comment by miykael** [comment]
@djarecka - thanks for the temporary fix. I actually fixed this in nilearn with (https://github.com/nilearn/nilearn/pull/1616) but it will take to the next release to have its effect.

**Comment by djarecka** [comment]
Great, so let's keep this temporary fix until `nilearn` have a new release!

**Comment by miykael** [comment]
@djarecka, `nilearn` took now care of this with [version 0.4.1](http://nilearn.github.io/whats_new.html#bug-fixes). Took care of the temporal fix with https://github.com/miykael/nipype_tutorial/commit/2780a09017ff270c064e2d8e66bef12b729c3745.
