### ISSUE TITLE
Reducing docker image size

### ISSUE THREAD

**Issue by miykael** [miykael/nipype_tutorial#54]
@djarecka - picking up your point from https://neurostars.org/t/datacamp-nipype-tutorial/1434/5.

**Dataset**
It might make sense to take the dataset out from the docker image? I saw in my workshop last weekend, that a big docker image can cause a lot of delay and it might be easier to either download additional data when needed or give it to user at a workshop via USB-key.

I also did some investigation and have another solution:
1. ***Deleting derivatives/freesurfer*** - This folder contains currently 1 subject and takes up 250MB, even though we never use this subject.
2. ***Deleting derivatives/fmriprep*** - Even though I am a fan of fmriprep, we use it almost exclusively in the examples and it takes up 150MB per subject.
3. I'm not sure if we should also kick out the ***mni_icbm152_nlin_asym_09c*** image that takes 165MB as we use it only for the ANTs normalization example. We could insert a download cell in this example.

Those reduction would leave us with 64MB per subject. So, to keep it really small, should we just keep 1 or 2 subjects? What do you think?

**Software**
Concerning software: SPM takes almost 3GB in space, ANTs and FSL seem to be rather small. I think we should leave SPM in there, as it is used by so many users. What do you think?

**Comment by djarecka** [comment]
Hi @miykael (I will CC: @satra , he might also have opinion),

**Dataset**
 - I believed in Boston we used container without data and ask people to mount data (after installing with datalad) and this led to issues too. Both, downloading data (that you can skip if you give usb) and mounting volume for people who did not have experience. So we decided to include in the container because it's easier. I can see that this might cause delays, but you can always ask people to pull the image earlier, so you don't have 30 people pulling at the same time, and you're sure that you don't need anything more.

- Of course, for workshops we can experiment various options (it also depends if this is nipype only etc.), but  having an image with data in the repo allows us for easy testing, using binder, and easier start for users who just found this tutorial online.

- the problem with 2 subjects only is that statistics from `example*` wouldn't make too much sense (note that we even have 2 groups now, left- and right-handed), agree that for the first introductory notebooks 2 subjects are totally fine.

- regarding `derivatives` we are using them in `example*` notebooks, however it is very likely that we can have much smaller subset of data. I spent some time to came up with datalad command that downloads everything and is not too long, but didn't really check how much smaller it can be.

** software**
I agree, if SPM is a popular tool, it might be useful to keep.

**general**
the point that I tried to make, was that if you concentrate on introductory notebooks only, you can make image smaller. Perhaps we can create a second smaller image for people who only want to try Nipype without going to `example*` notebooks? We could also probably remove SPM from the smaller one.

**Comment by satra** [comment]
a few comments:

- isn't the point of using datalad inside the container that no data needs to be in the image itself but can be downloaded as necessary? and thereby only the minimal pieces actually exist. (if there are technical issues, they should be resolved, but conceptually this should be the idea).

- a tutorial notebook can check in an opening cell what data it needs and **downloads just those bits.**

- a dependent tutorial can also check if the previous tutorial has been run, and if not, inform the user that they should run the previous tutorial. so some tutorials can be stand alone and some are dependent.

- for the specific tutorial (as opposed to a generic nipype container), one can use reprozip to minimize the container to its smallest size. (neurodocker has instructions on how to achieve this using neurodocker)

**Comment by djarecka** [comment]
@satra,
- agree that having datalad allows downloading files later. And one of the notebooks did it, however I included in the Dockerfile itself for various reasons, that not sure if remember all of them now... I think main point was to avoid problems when `get` doesn't work, etc.,  so people having the docker image don't have to worry about anything (they don't even have to have internet connection). Second reason was that users have to wait for the image, but don't have to wait later when executing the notebooks.

 But your solution with doing this in the first cell might be better. The downside during workshop would be that everyone starts downloading the same data at the same time and also at the time that you as an instructor want to move forward with the notebook.

The only notebooks that require previous ones are `example*`

**Comment by satra** [comment]
i would recommend workshop specific containers. the intent here for nipype tutorials is to either run on binder or run yourself.

**Comment by miykael** [comment]
@satra, good point. It's a quick thing to add data to workshop images.

@djarecka, I'm happy to adapt everything, except if you're already on it and want to do it? I would leave one subject in the datafolder (about 65MB) and add datalad get steps where otherwise necessary. I will also look into reprozip to minimize the container.

**Comment by djarecka** [comment]
@miykael - sorry for late answer. No I haven't started doing anything and I won't have time to work more on the tutorial this week, can help next week.

FYI: I was recently complaining that sometimes I have to retry multiple times datalad `get` command to really get all files needed for the tutorial.  I know that Yarik is planning to update datalad and we should have a new release this week. The new version should also work without the git configuration (the reason why I'm not using the most current one). Not sure if you want to wait, but next week we should test the new version anyway.

I agree that this might be a starting point for workshop, but usually you need some adjustment anyway etc. So @satra idea to include downloading part at the beginning of the notebooks can work very well. I'm just not sure about Binder, I sometimes had to retry multiple times building the container, but once it's created, the launching is fast (if it works). But let's test it! 
Also, the biggest problem I expect we can have with `example*` notebooks, but  they might not work with Binder for other reasons too... And I still believe that people who try `example*` notebooks should be probably interested in running Nipype locally anyway, so we don't necessarily have to concentrate on them.

**Comment by miykael** [comment]
@djarecka - I was curious, so I reduced the docker image with https://github.com/miykael/nipype_tutorial/commit/af835069196fbc201cd31ae350c0c3fe3bbe15d9 to 7.54GB. For the moment, I kept the 10 subjects anat and one functional, as that only uses 384MB. I also suppressed the `-J4` flag in datalad and removed your failure checks (under the assumption that they are caused by the`-J4` flag). Please, reverse these changes if I broke something now.

But I wasn't able to use reprozip with neurodocker to minimize the image, yet. I used the instructions from [neurodocker](https://github.com/kaczmarj/neurodocker#minimize-existing-docker-image), but got some errors.

By the way, looking at the number of pulls (~225) of the `nipype_tutorial` on dockerhub, it seems to make sense to focus rather on binder than on heavy containers, as most people seem to be using just the homepage (google analytics shows me 1050 new users, 2860 sessions and 6645 page views since January 1st). What do you think?

**Comment by djarecka** [comment]
I'm not sure what do you mean by "focus rather on binder than on heavy containers", since we are using the same image for Binder and CircleCI, so I'd rather improve it, e.g. as @satra suggested.

Regarding statistics, the way how I see it, is that the tutorial has two group of users. One that just want to look around, since they've heard about Nipype, if they have Binder they can even execute some notebooks, but for some reason they won't use Nipype in their work. For the second group of user the tutorial is a starting point for using Nipype in their work. The second group is much smaller, but for these users having a container that they can pull to run notebooks locally and experiment with their own data might be really useful IMO. So I'd try to have in DockerHub something that it's working for all notebooks. I don't really know if 8-10G  image  is too large for most people, I'd guess that it's not (not saying that we shouldn't try to decrease the size).

Regarding your changes, I believe that after removing this data the test would fail now. If you push directly to master, CircleCI doesn't run tests. I've actually just noticed that for PRs that are not mine (e.g. #51) CircleCI is also not running. Can you please check the CircleCI configurations, so it runs tests for all PRs? I think I can't do it for you, I can only set for my PR (and this is working).

**Comment by miykael** [comment]
Sorry, I meant that most users seem to be using just the homepage, and not the docker image. But you're right, it makes most sense to have a good running image for Binder and CircleCI.

I don't think that 8-10GB is too big for most people, but it causes often huge issues at workshops :-)

Regarding the CircleCI configurations, I've turned on "Build forked pull requests - Run builds for pull requests from forks". I also saw that we could add [parallelism](https://circleci.com/docs/2.0/configuration-reference/#parallelism), to our `config.yml` file, would that help? I think we could set it up to 4.

**Comment by miykael** [comment]
Concerning workshops: Unfortunately, I have already seen it twice that people start downloading docker images during the workshop. But this can be handled by putting docker images on USB-keys. The much bigger issue is getting Docker to run on Windows and not running into RAM issues... :-)

Yes, the new datalad version [0.9.3](https://github.com/datalad/datalad/releases/tag/0.9.3) was just released. I've updated it with https://github.com/miykael/nipype_tutorial/commit/f76a56e9c642fa3b0014947e35bbf1f2fbc37c9a. I will later look into the tutorials and update the notebook.

About the parallelism, you're right. It doesn't make sense to use that for the tutorials.

Do you have any expertise to with reprozip and can you give it a try to minimize the docker image?

**Comment by djarecka** [comment]
I don't have experience with reprozip, but I can try it.

**Comment by djarecka** [comment]
does the new version of datalad work with our dockerfile?

**Comment by miykael** [comment]
Locally, yes. I had no issue building the docker image from the dockerfile. But on CircleCI, I again got the 
 `Unable to find image 'djarecka/nipype_tutorial:master' locally` error (see https://circleci.com/gh/miykael/nipype_tutorial/22) that I don't know how to solve, except for changing `$CIRCLE_BRANCH` to `latest`.

**Comment by djarecka** [comment]
I actually don't know why CircleCI doesn't show error at the "docker built" part and stop there..., but the problem with docker built is the reason CircleCI fails (see the logs of docker built part). in the "docker run" part it simply can't find the image that previously failed to build. There are some problems with SPM that I saw earlier today, don't think it's our fault. Hope, this will be solved.

**Comment by djarecka** [comment]
@miykael - the issue with spm is gone, so if you try to rebuild your CIrcleCI you should get the same as I [got](https://circleci.com/gh/djarecka/nipype_tutorial/85?utm_campaign=build-failed&utm_medium=email&utm_source=notification). image is fine, and introductory tests passed but 4 notebooks are failing because there are no derivatives.

**Comment by miykael** [comment]
I had some typos and wrong dependencies that were corrected with https://github.com/miykael/nipype_tutorial/commit/9c646ebb52b95ec93c524a8146b8cdf3470af6b3, the tests should now pass (hopefully).

But I saw that the normalization with ANTs is now not correct anymore (might be an issue with the fmriprep warp.h5 that we are using. I'm currently looking into that.

**Comment by satra** [comment]
@miykael - fmriprep warp has to be applied to derived T1space data. it cannot be applied to the raw T1 data.

**Comment by miykael** [comment]
@satra - thanks, that's what I assumed. Than I will use datalad within the preprocessing example to get all necessary data.

**Comment by miykael** [comment]
Sorry for the confusing commits... The notebook now uses exclusively anatomical derivatives from fmriprep for the examples. The required data is downloaded with datalad in the preprocessing example, and the normalization example (the warp parameters for ANTS).

The docker image only downloads `sub-01` for the basic notebooks and the ICBM template `1mm_T1.nii.gz`.

@djarecka - the [automatic build on DockerHub](https://hub.docker.com/r/miykael/nipype_tutorial/builds/) seems to be working again. Under those circumstances, is it ok for you that we change `djarecka/nipype_tutorial` to `miykael/nipype_tutorial` in all the `docker` commands?

@satra - In the docker image, conda has a subfolder `pkgs` of ~500MB size. I think this is independent of the `neuro` environment. The notebooks seem to run even without this folder. Do you know if it is save to empty this folder?

**Comment by djarecka** [comment]
@miykael - sure, you can change the commands. 

I was also  wondering if you wouldn't mind to create PRs even for your changes. You can always merge it, but the advantage of PR is that CircleCI runs tests and the output of the tests is easily accessible by anyone through the repo. Right now I merge this changes to my master, so my CircleCI runs the tests, to see the output. But, it is just a suggestion, don't want to change your workflow too much.

**Comment by satra** [comment]
@miykael - the conda environment should not have in pkgs - that should be taken care of by `conda clean -tipsy` if created by `neurodocker`. perhaps @kaczmarj can comment.

**Comment by miykael** [comment]
@djarecka - of course, I actually thought that there need to be an alternative on how to comment on my changes, than through issues... I must admit, I don't know how to create PRs on my own repos and it therefore hasn't crossed my mind. I didn't find an option on github or git. How can I do that? Do I need to work through branches or is there an alternative?

**Comment by djarecka** [comment]
@miykael - I think you can't do it without creating a new branch (at least can't imagine how). I personally love branches and almost never work on master, once I have a different branch github gives me an option to compare with master and to create a PR.

**Comment by kaczmarj** [comment]
It looks like the `pkgs/` directory contains packages that are linked to environments [source](https://conda.io/docs/user-guide/concepts.html#conda-directory-structure)

> Also referred to as PKGS_DIR. This directory contains decompressed packages, ready to be linked in conda environments. Each package resides in a subdirectory corresponding to its canonical name.

`conda clean -tipsy` doesn't find anything to remove.

```
[host]$ docker run --rm -it -uroot miykael/nipype_tutorial:latest bash
root@00d324782415:/home/neuro# conda clean -tipsy
Cache location: 
There are no tarballs to remove
Cache location: 
There are no unused packages to remove
source cache (/opt/conda/conda-bld/src_cache)
Size:                                           0 B

git cache (/opt/conda/conda-bld/git_cache)
Size:                                           0 B

hg cache (/opt/conda/conda-bld/hg_cache)
Size:                                           0 B

svn cache (/opt/conda/conda-bld/svn_cache)
Size:                                           0 B

Total:                                          0 B
Removing /opt/conda/conda-bld/src_cache
Removing /opt/conda/conda-bld/git_cache
Removing /opt/conda/conda-bld/hg_cache
Removing /opt/conda/conda-bld/svn_cache
root@00d324782415:/home/neuro# 
```

@miykael - usually my flow is to develop in a branch other than master (`git checkout -b add/feature`) and then I submit a PR within my own project to merge `add/feature` into `master`. You can also open a PR and then continue adding commits, and if you have CI tests in place, they will run on each push.

**Comment by miykael** [comment]
@djarecka and  @kaczmarj - thank you for the nice explanation about the PRs. It makes so much more sense to have also PRs on my repo and having CI test in place before merging.

@kaczmarj - exactly, `conda clean -tipsy` doesn't find anything. If I understand it correctly, they would allow faster package retrieval in environments but are not needed for the environment to run, correct? If yes, than I will empty this folder for the `nipype_tutorial`, which frees up ~540MB.
Perhaps it makes sense to have such a cleanup also in `neurodocker`?

**Comment by kaczmarj** [comment]
@miykael - i am now sure whether the `pkgs/` directory is necessary for runtime. we can delete it and see if the tutorials run :)

**Comment by miykael** [comment]
@kaczmarj - we will see if it works, but `pkgs` is now cleaned out manually in https://github.com/miykael/nipype_tutorial/pull/56, reducing the image size be 540MB.

@djarecka - I think, for the moment that's the best I can do with reducing the docker image. If you have more suggestions, I'm happy to look into them, but otherwise, I would close this issue. (And in the future work directly on branches and do PRs for those kind of thigs, instead of using issues :-) )
