### ISSUE TITLE
Tutorial on homepage with or without figures?

### ISSUE THREAD

**Issue by miykael** [miykael/nipype_tutorial#55]
@djarecka - I have a question about the output figures in the notebooks (in particular the examples). Currently on the homepage we've suppressed all figures, and therefore sections like [this](https://miykael.github.io/nipype_tutorial/notebooks/example_1stlevel.html#Visualize-results) look rather dull.

My main reason for excluding the figures was to keep notebook size on github small, as well as letting the user discover the figures for themselves. In the docker image and on mybinder, I recommend to still omit the figures. But on the homepage, I'm curious if it might not be nicer to leave them in. Like this, user see on the homepage what the output would be, if the notebooks were run. What do you think?

**Comment by djarecka** [comment]
@miykael I agree with you. Actually at the beginning I was wondering if keeping all the outputs. However as you said it doesn't motivate people who have access to notebooks to really run them (homepage is created automatically, so it has to be the same).

Maybe keeping just some plots in the examples would be a good solution.

**Comment by miykael** [comment]
@djarecka - the homepage isn't actually created automatically. Well, the [update_gh-pages.sh](https://github.com/miykael/nipype_tutorial/blob/master/update_gh-pages.sh), does it automatcially. Anyhow, this means that we can decide which version of the notebooks we want to have on the gh-pages.

I've run all the notebooks and left all of the figures and most of the outputs and logs in there and updated the gh-pages with https://github.com/miykael/nipype_tutorial/commit/ec7466021ab14c8876f82c9db4ad9c3d0749afa0. I will see how much of a hassle it is to updated the gh-pages manually (i.e. also running the notebooks to keep the figures). But I think it's much nicer like this: https://miykael.github.io/nipype_tutorial/notebooks/example_2ndlevel.html#Visualize-results

What do you think? You can close the issue if that's all fine with you.

**Comment by djarecka** [comment]
@miykael - let me understand it, because I'm a little confused with these pages. So you're saying that github builds the page using `update-gh-pages.sh` script?  Because you're not running this script on your own, correct?

I do agree that with figures looks better, just not sure how much hassle it will be.

**Comment by miykael** [comment]
@djarecka - no, I'm still using a manual approach (coming from the beginner's guide). I run the `update-gh-pages.sh` myself. It serves me more as a summary of the commands to have it all together. Like this it allows me to create the notebooks with output, and I also add some additional things (google analytics tracker etc.).

It's another thing that I actually don't know. How would it work if I wanted the `gh-pages` to be generated automatically?

**Comment by djarecka** [comment]
sorry, I mixed two things together...

I forgot that the automatic option that Satra showed me, and I mentioned at some point, was using `nbviewer`: http://nbviewer.jupyter.org/github/miykael/nipype_tutorial/blob/master/index.ipynb

This is generated automatically, not sure if there are any disadvantages

**Comment by djarecka** [comment]
Sure! Just let me know what I should do whenever I'm changing master, it looks like I haven't been updating website properly.

**Comment by miykael** [comment]
No worries, I usually try to update it within 24h. Otherwise, running the commands in https://github.com/miykael/nipype_tutorial/blob/master/update_gh-pages.sh step by step should do the trick.

But I don't recommend to run the script directly. I have some `git push`, `git checkout` and some nice `rm -rf` in there. So if git cannot checkout the `gh-pages`, it might delete your current branch... Saying it out loud, I should do something about that.

**Comment by djarecka** [comment]
@miykael yes, I remember, I used to comment the `rm` part just in case ;-)

But I was wondering what would be your recommendations when I change notebooks, should I just keep entire output?

**Comment by miykael** [comment]
Yes, entire notebooks is good. I only kicked out the following things:
- workflow log that were really long (~ more than 200-300 lines of code, where it just becomes endless scrolling)
- `tree /folderpath` if it also gives endless scrolling cells
- the `datalad -J4` outputs: but just because they look weird in notebooks.

But anyhow, it's not an issue if all of them stay in there. I just want to prevent that most of the notebook is some log output. But don't waste your time with cleaning :-)

**Comment by miykael** [comment]
Closing this issue as it is solved/finished, at least for the moment.
