### ISSUE TITLE
Prevention of docker build on circleci

### ISSUE THREAD

**Issue by miykael** [miykael/nipype_tutorial#61]
When running the tests on CircleCI, we have a step called `docker build`, see for example https://circleci.com/gh/miykael/nipype_tutorial/48. Now, this means that circleci, builds the docker image for every new PR. This because our Dockerfile contains all the instructions for the environment.

Now, for most of our PRs only the notebooks change. We could therefore put the first part of the Dockerfile in another docker image and import this in the `nipype_tutorial` Dockerfile. As a consequence, circleci, wouldn't need to rebuild the whole build, but could directly download the first part from dockerhub.

@djarecka - What do you think? Does this make sense?

**Comment by djarecka** [comment]
sure, but the advantage of building the image is that it takes the newest version, so we would have to remember to update the base image. Would definitely keep nipype (and maybe all python libraries) in the part that id building with circle

**Comment by miykael** [comment]
You're right. I forgot that sometimes the Dockerfile stays the same, but the dependencies change (newer version of nipype etc.).

It would be possible to specify a dependency of builds on dockerhub. But setting all this up, might not be worth the 15min faster build.

**Comment by miykael** [comment]
Closing issues.
