### ISSUE TITLE
testing nbval for the notebooks testing

### ISSUE THREAD

**Issue by djarecka** [miykael/nipype_tutorial#62]
Just learned about pytest plugin to jupyter: https://github.com/computationalmodelling/nbval

Might be worth trying if it's better than the current testing approach.

**Comment by miykael** [comment]
@djarecka - cool, I didn't know that this exist. Depending on how it works I have some concerns.
- If it only tests those cells that we want to tests, it might be useful (but time consuming to set it up?).
- If it tests all cells, how would it handle cells with pipeline stream output (`.run(...)`), how would it handle `write_graph()` figures that also change often?

**Comment by djarecka** [comment]
@miykael - I agree with you that this might not be the best solution for us, and I'm relatively happy with the solution we have. 
I'll have to lear a bit more before mid May, since will be helping with a workshop that will be use it. I can write more once I have some experience.

**Comment by miykael** [comment]
This issue can be closed after https://github.com/miykael/nipype_tutorial/pull/91 is merged.
