### ISSUE TITLE
adding Oscar's notebooks

### ISSUE THREAD

**Issue by djarecka** [miykael/nipype_tutorial#63]
see https://github.com/nipy/nipype/issues/2528

**Comment by djarecka** [comment]
@miykael - any thoughts? I can start adjusting the notebooks, but will probably need your help

**Comment by djarecka** [comment]
@miykael I was thinking about doing it during weekend or next week, since have to do other things this week. If you have time and want to do it, I'm happy to work on other advanced tutorial later. Just let me know or open PR, so we both don't work on it.

**Comment by miykael** [comment]
@djarecka  - I'm happy to look into this, i.e. start in a new PR and will let you know if and where I get stuck.

**Comment by miykael** [comment]
Oscar's notebook about "how to create interfaces" will be added with https://github.com/miykael/nipype_tutorial/pull/72.
