### ISSUE TITLE
Nipype tutorial dataset derivatives not accessible anymore via datalad

### ISSUE THREAD

**Issue by miykael** [miykael/nipype_tutorial#79]
The nipype_tutorial is currently using the [OpenfMRI dataset ds000114](https://openfmri.org/dataset/ds000114/). We're downloading the dataset with:
```
datalad install -r ///workshops/nih-2017/ds000114
```

Since yesterday, downloading `freesurfer` and `fmriprep` derivatives, leads to the following error:
```
datalad get -r /data/ds000114/derivatives/fmriprep/sub-01.html 
Total (0 ok, 1 failed out of 1):   0%|     | 0.00/20.1M [00:00<?, ?B/s][WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[ERROR  ] from web...                                                                                                                                                                                        
| from web...
| Unable to access these remotes: web
| Try making some of these repositories available:
| 	0000...0001 -- web
|  	b8b7...8eb9 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/workshops/nih-workshop-2017/ds000114/derivatives/fmriprep
|  [get(/data/ds000114/derivatives/fmriprep/sub-01.html)] 
get(error): /data/ds000114/derivatives/fmriprep/sub-01.html (file) [from web...
from web...
Unable to access these remotes: web
Try making some of these repositories available:
	0000...0001 -- web
 	b8b7...8eb9 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/workshops/nih-workshop-2017/ds000114/derivatives/fmriprep
]
```

Unfortunately, I don't know exactly who to contact to tackle this `Unable to access these remotes: web` error.

@chrisfilo - I think it would make sense to move away from **`datalad ///workshop`** and use a dataset from [OpenNeuro](https://openneuro.org/). But I haven't found your `ds000114` dataset on OpenNeuro. Is it there or otherwise, could it be uploaded? I'm of course also open to take another dataset, but I think the ds000114 has a lot to offer, while still being rather small.
Thanks for your help.

**Comment by miykael** [comment]
Correction, I found the OpenfMRI `ds000114` dataset on OpenNeuro as [`ds000108`](https://openneuro.org/datasets/ds000108). But I have two follow up problems:
1. How can I download an OpenNeuro dataset via `datalad`?
2. [`ds000108`](https://openneuro.org/datasets/ds000108) doesn't have derivatives available. If we want to keep this dataset for the nipype tutorial, we would need the `fmriprep` and `freesurfer` output.

**Comment by miykael** [comment]
Hi @yarikoptic - I just realized that you might be able to help with this issue. If I'm not mistaken, than `yoh@smaug` is actually you? As you can see above, `datalad` cannot access anymore the dataset under
```
yoh@smaug: /mnt/btrfs/datasets/datalad/crawl/workshops/nih-workshop-2017/ds000114/derivatives
```

Do you have any insights what might have happened?

**Comment by djarecka** [comment]
@miykael -  I was just testing and I'm able to get the file `derivatives/fmriprep/sub-01.html `. Can you check again now? Could be just a temporary problem.

**Comment by miykael** [comment]
Thanks @djarecka! Yes, everything works again :+1:

Nonetheless, would it make sense to move away from `workshops/nih-workshop-2017` and to create a "new dataset" for the nipype_tutorial?

**Comment by djarecka** [comment]
I think @satra and others really like this dataset and that why we used it during the Nipype Workshop last year. You don't like this dataset?
I spent quite some time adjusting the tutorial to this dataset last summer, so I'd probably want to do it again without a good reason ;-)

**Comment by djarecka** [comment]
or do you mean just moving this dataset somewhere else?

**Comment by djarecka** [comment]
Yes, it did happen to me a few times that I couldn't access the dataset, but not sure if with other services problems would occur less often.

Unfortunately, I don't know too much about interaction between `datalad` and OpenNeuro.org, have no experience.
 
@yarikoptic - do you have any thoughts?

**Comment by satra** [comment]
@miykael - there are a few pieces here:

1. the main dataset does come from openneuro (if there is a change of dataset id, we should also fix that)
2. the derivatives used to come from dropbox since they are not available from openneuro yet (perhaps @chrisfilo can reconfirm)
3. then yarik copied them over to smaug i think

datalad stitches them together as separate repos. 

@yarikoptic - did we lose the dropbox remotes?

**Comment by djarecka** [comment]
@satra - I think it's working now

**Comment by chrisfilo** [comment]
Couple of things:
- ds000114 is mislabeled on OpenNeuro as ds000108 @rwblair is working on fixing this. It will revert to it's proper accession number soon.
- Derivatives generated by all jobs are accessible via s3 
![image](https://user-images.githubusercontent.com/238759/39477225-7690744e-4d13-11e8-8e13-35f852a0c9b2.png)

**Comment by satra** [comment]
@chrisfilo - but that does not give me individual URLs for every file that's in the derivatives output. we would essentially need a listing of every URL, and hopefully with versioning.

**Comment by chrisfilo** [comment]
You can generate the list of all files and their URLs via the S3 API. Example: https://s3.amazonaws.com/openneuro.outputs/447d26e4f9fe6ce7b5ff851356280f6a/dae3c6ba-9b1f-471e-b54d-64c9cfc34f91/reports/bold_group.html

Job results are not overwritten. Each job has its own subfolder so there is no need for versioning.

**Comment by yarikoptic** [comment]
Sorry that I cam late to this fun... but original problem seems to be resolved I guess since it works for me fine:
```shell
$> datalad install -r ///workshops/nih-2017/ds000114
...
$> datalad get -r ds000114/derivatives/fmriprep/sub-01.html      
get(ok): /tmp/ds000114/derivatives/fmriprep/sub-01.html (file) [from web...                           
checksum...] 
```
 In general, you could "interrogate" what annex knows about file availability:
```shell
$> cd ds000114/derivatives/fmriprep/
sub-01/       sub-02.html@  sub-04/       sub-05.html@  sub-07/       sub-08.html@  sub-10/
sub-01.html@  sub-03/       sub-04.html@  sub-06/       sub-07.html@  sub-09/       sub-10.html@
sub-02/       sub-03.html@  sub-05/       sub-06.html@  sub-08/       sub-09.html@

$> git annex whereis sub-01.html
whereis sub-01.html (2 copies) 
  	00000000-0000-0000-0000-000000000001 -- web
   	b8b7bab3-c978-4f50-8ed4-e77900198eb9 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/workshops/nih-workshop-2017/ds000114/derivatives/fmriprep

  web: https://dl.dropbox.com/s/f03sxu7omhsibyc/sub-01.html?dl=0
ok
```
and indeed smaug is my server (I love how git-annex is [FAIR](https://www.go-fair.org/fair-principles/)) and we have a single web url for it.  If issue with dropbox persists/reoccurs, we could host those also from our server

With what other files there is a problem ATM?

**Comment by yarikoptic** [comment]
BTW, @satra if need quickly, then `datalad ls -r -L s3://openneuro/ds000108/ds000108_R2.0.0/uncompressed/sub-01/ ` would list http urls for the most recent version (if want all, add `-a`) and check if it is accessible  (output is a big too wide, see the rightmost):
```shell

$> datalad ls -r -L s3://openneuro/ds000108/ds000108_R2.0.0/uncompressed/sub-01/ 
Connecting to bucket: openneuro
[INFO   ] S3 session: Connecting to the bucket openneuro 
Bucket info:
  Versioning: S3ResponseError: 403 Forbidden
     Website: S3ResponseError: 403 Forbidden
         ACL: S3ResponseError: 403 Forbidden
ds000108/ds000108_R2.0.0/uncompressed/sub-01/anat/sub-01_T1w.nii.gz                                2017-11-18T12:38:37.000Z  4682289 ver:lV0.oMt3agO97O1kUrc4NnvMDMlEYiLb  acl:AccessDenied  http://openneuro.s3.amazonaws.com/ds000108/ds000108_R2.0.0/uncompressed/sub-01/anat/sub-01_T1w.nii.gz?versionId=lV0.oMt3agO97O1kUrc4NnvMDMlEYiLb [OK]
ds000108/ds000108_R2.0.0/uncompressed/sub-01/func/sub-01_task-Emotionregulation_run-01_bold.nii.gz 2017-11-18T12:38:37.000Z 23115394 ver:iDP0ORbdlrpDJZo2zRAN_Qotfmq0eFZV  acl:AccessDenied  http://openneuro.s3.amazonaws.com/ds000108/ds000108_R2.0.0/uncompressed/sub-01/func/sub-01_task-Emotionregulation_run-01_bold.nii.gz?versionId=iDP0ORbdlrpDJZo2zRAN_Qotfmq0eFZV [OK]
...
```

**Comment by yarikoptic** [comment]
FWIW we are now providing  all content for that dataset from datasets.datalad.org so no longer at mercy of dropbox ;)

**Comment by satra** [comment]
thanks yarik. does this also include derivatives now?

**Comment by yarikoptic** [comment]
yes, everything and http://datasets.datalad.org/?dir=/workshops/nih-2017 shows 17G now (upstairs might still be outdated ;) )

**Comment by miykael** [comment]
Thank you everyone for the effort! And especially thank you @yarikoptic for putting all on datasets.datalad.org :+1:

**Comment by yarikoptic** [comment]
glad to help! enjoy

**Comment by miykael** [comment]
Follow up question - I still get the same error message, when I try to download the derivatives from within the `nipype_tutorial` docker container. But I think this is rather a docker issue / access issue. Nonetheless, @yarikoptic, perhaps you see quickly where the problem is?

The problem unfolds as follows. If I run the `nipype_tutorial` container:

```docker run -it --rm -p 8888:8888 miykael/nipype_tutorial bash```

Then, within the docker container, I run:
```
$ datalad install -r ///workshops/nih-2017/ds000114
[INFO   ] Cloning http://datasets.datalad.org/workshops/nih-2017/ds000114 to '/home/neuro/nipype_tutorial/ds000114' 
[INFO   ] access to dataset sibling "datalad" not auto-enabled, enable with:
|       datalad siblings -d "/home/neuro/nipype_tutorial/ds000114" enable -s datalad 
install(ok): /home/neuro/nipype_tutorial/ds000114 (dataset)
[INFO   ] Installing <Dataset path=/home/neuro/nipype_tutorial/ds000114> recursively 
[INFO   ] Cloning http://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/fmriprep/.git to '/home/neuro/nipype_tutorial/ds000114/derivatives/fmriprep' 
install(ok): derivatives/fmriprep (dataset) [Installed subdataset <Dataset path=/home/neuro/nipype_tutorial/ds000114/derivatives/fmriprep>]
[INFO   ] Cloning http://datasets.datalad.org/workshops/nih-2017/ds000114/derivatives/freesurfer/.git to '/home/neuro/nipype_tutorial/ds000114/derivatives/freesurfer' 
install(ok): derivatives/freesurfer (dataset) [Installed subdataset <Dataset path=/home/neuro/nipype_tutorial/ds000114/derivatives/freesurfer>]
action summary:
  install (ok: 3)
```

Followed by:

```
$ datalad get ds000114/derivatives/fmriprep/sub-01.html 
Total (0 ok, 1 failed out of 1):   0%|                                                                                                                                | 0.00/20.1M [00:00<?, ?B/s][WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[ERROR  ] from web...                                                                                                                                                                                        
| from web...
| Unable to access these remotes: web
| Try making some of these repositories available:
|   00000000-0000-0000-0000-000000000001 -- web
|   b8b7bab3-c978-4f50-8ed4-e77900198eb9 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/workshops/nih-workshop-2017/ds000114/derivatives/fmriprep
|  [get(/home/neuro/nipype_tutorial/ds000114/derivatives/fmriprep/sub-01.html)] 
get(error): /home/neuro/nipype_tutorial/ds000114/derivatives/fmriprep/sub-01.html (file) [from web...
from web...
Unable to access these remotes: web
Try making some of these repositories available:
    00000000-0000-0000-0000-000000000001 -- web
    b8b7bab3-c978-4f50-8ed4-e77900198eb9 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/workshops/nih-workshop-2017/ds000114/derivatives/fmriprep
]
```

But if I run the `datalad` command on my OS (i.e. not in a docker container), it all works fine.

**Comment by yarikoptic** [comment]
I think it might be older git annex within docker, could you check version? Recent one should be much more robust

**Comment by miykael** [comment]
@yarikoptic - the git annex version is
```
$ git annex version
git-annex version: 6.20180416+gitg86b18966f-1~ndall+1
build flags: Assistant Webapp Pairing S3(multipartupload)(storageclasses) WebDAV Inotify DBus DesktopNotify ConcurrentOutput TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.14.1 bloomfilter-2.0.1.0 cryptonite-0.20 DAV-1.3.1 feed-0.3.11.1 ghc-8.0.1 http-client-0.4.31.1 persistent-sqlite-2.6 torrent-10000.0.0 uuid-1.3.12 yesod-1.4.3
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar hook external
local repository version: unknown
supported repository versions: 3 5 6
upgrade supported from repository versions: 0 1 2 3 4 5
operating system: linux x86_64
```

**Comment by miykael** [comment]
@djarecka - yes, unfortunately it happens on CircleCI. That's where I learned about this issue. What is strange, is that even if I [rerun an old CircleCI build](https://circleci.com/gh/miykael/nipype_tutorial/126) that passed 8 day ago, I get issues with datalad's download of the derivatives (the main dataset works well).

**Comment by miykael** [comment]
The issue was resolved with https://github.com/datalad/datalad/issues/2472#issuecomment-386889111 and the tutorial should work again as before!

**Comment by wulms** [comment]
Hey @miykael, I started using your tutorials and when I try to run your datalad code I do also encounter errors :/

`datalad get -J 4 /data/ds000114/derivatives/fmriprep/sub-*/anat/*preproc.nii.gz \
                /data/ds000114/sub-01/ses-test/anat \
                /data/ds000114/sub-*/ses-test/func/*fingerfootlips*`

output:
`[WARNING] path not associated with any dataset [get(/data/ds000114/derivatives/fmriprep/sub-*/anat/*preproc.nii.gz)] 
get(impossible): /data/ds000114/derivatives/fmriprep/sub-*/anat/*preproc.nii.gz [path not associated with any dataset]
[WARNING] path not associated with any dataset [get(/data/ds000114/sub-01/ses-test/anat)] 
get(impossible): /data/ds000114/sub-01/ses-test/anat [path not associated with any dataset]
[WARNING] path not associated with any dataset [get(/data/ds000114/sub-*/ses-test/func/*fingerfootlips*)] 
get(impossible): /data/ds000114/sub-*/ses-test/func/*fingerfootlips* [path not associated with any dataset]
action summary:
  get (impossible: 3)`

**Comment by satra** [comment]
@yarikoptic - did you change some data?

**Comment by djarecka** [comment]
@mkvanvugt - just double checking - are you using the current version of the notebook? the datalad command has been updated 2 weeks ago (to datalad 0.12)
(fyi. you might have some other issues, that we are dubugging right now, but datalad should work)

**Comment by mkvanvugt** [comment]
Yes, I was trying
 %%bash
datalad get -J 4 /data/ds000114/sub-0[234789]/ses-test/anat/sub-0[234789]_ses-test_T1w.nii.gz \
                /data/ds000114/sub-0[234789]/ses-test/func/*fingerfootlips*

**Comment by mkvanvugt** [comment]
result:
get(error): /data/ds000114/sub-02/ses-test/anat/sub-02_ses-test_T1w.nii.gz [path not associated with dataset <Dataset path=/home/neuro/nipype_tutorial>]
get(error): /data/ds000114/sub-02/ses-test/func/sub-02_ses-test_task-fingerfootlips_bold.nii.gz [path not associated with dataset <Dataset path=/home/neuro/nipype_tutorial>]
action summary:
  get (error: 2)

**Comment by mkvanvugt** [comment]
last year the same command worked fine on my system (Mac OS) but I got a fresh install of the nipype tutorial and docker today

**Comment by yarikoptic** [comment]
It might be due to a change in 0.12 API/behavior, try `cd /data/ds000114` first (or specify `-d /data/ds000114`) and then getting corresponding paths within that dataset.  Like `git` we now require to know on what dataset (repository) we are operating on.

> @yarikoptic - did you change some data?

`git log` could tell, but AFAIK - I didn't ;)

**Comment by djarecka** [comment]
@mkvanvugt @yarikoptic -  the current  tutorial has been updated to datalad 0.12, so if you haven't updated datalad, that might be the reason

**Comment by mkvanvugt** [comment]
cd /data/ds000114 seems to do the trick (at least, it's still working on processing and not giving an error)

**Comment by mkvanvugt** [comment]
yes, it worked!

**Comment by gurraburra** [comment]
I just tried to run the tutorial using the docker image and got the following error when downloading the data:
`[ERROR] git-annex of version >= 7.20190503 is missing. Install  git-annex-standalone  from NeuroDebian (http://neuro.debian.net) [annexrepo.py:_check_git_annex_version:555] (MissingExternalDependency) `
