### ISSUE TITLE
Running docker container without arguments

### ISSUE THREAD

**Issue by ASVBPREAUBV** [miykael/nipype_tutorial#83]
refers to tutorial:
"jupyter notebook tells that you want to run directly the jupyter notebook command within the container. Alternatively, you can also use jupyter-lab, bash or ipython."

Is there a way to run the container without additional arguments?

example:
docker run -it --rm -p 8888:8888 miykael/nipype_tutorial

so WITHOUT "...88:8888 miykael/nipype_tutorial **jupyter notebook**"

**Comment by djarecka** [comment]
so you want to run without argument like `-p 8888:8888` or without the command "jupyter notebook"? 
Do you want to use notebooks within the container (if yes, `-p` would be required)

**Comment by ASVBPREAUBV** [comment]
Without the command "jupyter notebook"

**Comment by djarecka** [comment]
so `miykael/nipype_tutorial` container has `jupyter notebook` as default command, so if you don't specify anything it will try to start jupyter notebook anyway.
However you can always try `run -it --rm miykael/nipype_tutorial:latest bash` to start `bash` or you can modify the image, so it has a different default command

**Comment by miykael** [comment]
@ASVBPREAUBV - as @djarecka recommened, I would run the docker command with the `bash` command at the end or rewrite the Dockerfile for your case.

Does this solve your issue?

**Comment by ASVBPREAUBV** [comment]
Ja works perfect. thanks
